server:
  port: 9004
#配置日志级别
logging:
  level:
    root: warn
    cn.codemodel.dao: trace
  pattern:
    console: '%p%m%n'
eureka:
  client:
    service-url:
      defaultZone: http://eureka6866.com:6866/eureka/,http://eureka6867.com:6867/eureka/,http://eureka6868.com:6868/eureka/
  instance:
    prefer-ip-address: true
    instance-id: hbs-recruitment
spring:
  datasource:
    url: jdbc:mysql://39.105.51.126/hbs_recruitment?useUnicode=true&characterEncoding=utf8
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: hbs-recruitment
  redis:
    host: 39.105.51.126
mybatis-plus:
  mapper-locations: classpath*:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml