server:
  port: 6866
eureka:
  instance:
    hostname: eureka6866.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka6868.com:6868/eureka/,http://eureka6867.com:6867/eureka/
spring:
  application:
    name: hbs-eureka-6866
